
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int flecha = 14;
  public static final int porcentaje = 5;
  public static final int conj = 12;
  public static final int nombreConj = 13;
  public static final int llaveAbrir = 2;
  public static final int or = 8;
  public static final int punto = 7;
  public static final int erLlaves = 18;
  public static final int pComa = 6;
  public static final int EOF = 0;
  public static final int simboloEspecial = 19;
  public static final int notacion = 15;
  public static final int error = 1;
  public static final int comentarioMult = 22;
  public static final int comentario = 21;
  public static final int tld = 16;
  public static final int asterisco = 9;
  public static final int dosPuntos = 4;
  public static final int interrogacion = 11;
  public static final int lexemaEntrada = 20;
  public static final int suma = 10;
  public static final int llaveCerrar = 3;
  public static final int erComillas = 17;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "llaveAbrir",
  "llaveCerrar",
  "dosPuntos",
  "porcentaje",
  "pComa",
  "punto",
  "or",
  "asterisco",
  "suma",
  "interrogacion",
  "conj",
  "nombreConj",
  "flecha",
  "notacion",
  "tld",
  "erComillas",
  "erLlaves",
  "simboloEspecial",
  "lexemaEntrada",
  "comentario",
  "comentarioMult"
  };
}

